# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique='True', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
            },
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Catálogo',
                'verbose_name_plural': 'Catálogos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='Item')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.Area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='catalogo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidencias.Catalogo', verbose_name='Catalogo'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together=set([('nombre', 'area')]),
        ),
        migrations.AlterUniqueTogether(
            name='area',
            unique_together=set([('nombre', 'catalogo')]),
        ),
    ]
