# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nombre',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Área'),
        ),
    ]
